"""Detection signals for Provenance Guard.

Each signal looks at a piece of text and returns a score from 0.0 to 1.0.
Higher means "more likely AI-generated". Lower means "more likely human".

Signal 1 (this milestone): LLM classification using Groq. It judges the text
as a whole — tone, flow, and style — the way a careful reader would.

Signal 2 (added in Milestone 4): stylometric heuristics in pure Python.
"""

import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

# The model we use for the LLM signal. Free tier, same as earlier projects.
GROQ_MODEL = "llama-3.3-70b-versatile"

# We make one client and reuse it.
_client = None


def _get_client():
    """Create the Groq client once and reuse it."""
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set. Add it to your .env file.")
        _client = Groq(api_key=api_key)
    return _client


# The prompt we send to the model. We ask for a single number plus a short
# reason, returned as JSON so we can read it back reliably.
_SYSTEM_PROMPT = (
    "You are an expert text-forensics assistant. You judge whether a piece of "
    "text reads as written by a human or generated by an AI language model.\n\n"
    "IMPORTANT: Formal, polished, or academic writing is NOT by itself evidence "
    "of AI. Many humans write formally and well. Falsely accusing a human writer "
    "is the worst mistake you can make, so do not raise your score just because "
    "the text is clean or formal.\n\n"
    "Real AI tells (raise the score for these):\n"
    "- Generic filler phrases like 'it is important to note', 'furthermore', "
    "'in today's fast-paced world', 'plays a crucial role'.\n"
    "- Even, templated structure that hedges every point without committing.\n"
    "- Lack of concrete, specific detail, real examples, or a personal stance.\n"
    "- Balanced 'on one hand... on the other' framing with no real opinion.\n\n"
    "Human tells (lower the score for these):\n"
    "- Specific, substantive content and concrete detail, even if formal.\n"
    "- A clear personal voice, opinion, humor, or irregular rhythm.\n\n"
    "Reserve high scores (above 0.7) for text with clear AI tells. If the text "
    "is formal but specific and substantive, lean lower. When genuinely unsure, "
    "stay near 0.5."
)

_USER_PROMPT_TEMPLATE = (
    "Assess the following text. Reply with ONLY a JSON object of the form:\n"
    '{{"ai_probability": <number between 0 and 1>, "reasoning": "<one short '
    'sentence>"}}\n'
    "Where ai_probability is your confidence that the text is AI-generated "
    "(1.0 = certainly AI, 0.0 = certainly human, 0.5 = no idea).\n\n"
    "TEXT:\n"
    '"""\n{text}\n"""'
)


def llm_signal(text):
    """Signal 1: ask Groq how likely the text is AI-generated.

    Returns a dict:
        {
            "score": float,        # 0.0 - 1.0, higher = more likely AI
            "reasoning": str,      # the model's short explanation
            "ok": bool,            # True if the call succeeded
        }

    The score is always a float in [0, 1]. If the call fails, we return a
    neutral score of 0.5 and ok=False so the caller can decide what to do.
    """
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_PROMPT_TEMPLATE.format(text=text)},
            ],
            temperature=0.0,  # we want stable, repeatable scores
            response_format={"type": "json_object"},
        )
        raw = response.choices[0].message.content
        data = json.loads(raw)
        score = float(data.get("ai_probability", 0.5))
        # Keep the score inside [0, 1] no matter what the model returns.
        score = max(0.0, min(1.0, score))
        reasoning = str(data.get("reasoning", "")).strip()
        return {"score": score, "reasoning": reasoning, "ok": True}
    except Exception as exc:  # network error, bad JSON, missing key, etc.
        return {
            "score": 0.5,
            "reasoning": f"LLM signal failed: {exc}",
            "ok": False,
        }


# --- Signal 2: stylometric heuristics (pure Python) ---
#
# Calibration constants. These map a raw metric to a 0-1 "AI-likeness" where
# higher = more AI. They were chosen by looking at real numbers from clearly
# human and clearly AI sample texts (see planning.md, section 2).
#
# Sentence-length burstiness, measured as coefficient of variation (CV = std /
# mean of sentence word counts). Human writing is bursty (high CV); AI is
# uniform (low CV). Below CV_LOW we call it fully AI-like; above CV_HIGH fully
# human-like.
_CV_LOW = 0.20
_CV_HIGH = 0.70

# Type-token ratio (unique words / total words). Higher = more diverse =
# more human. This metric is noisy on short text, so it gets little weight.
_TTR_LOW = 0.50
_TTR_HIGH = 0.90

# Punctuation density (punctuation marks / total words). Used only as a weak
# extra hint; capped at this value when mapping to 0-1.
_PUNCT_MAX = 0.20

# Weights of the three metrics inside the stylometric score. Burstiness is the
# strongest stylometric tell, so it dominates.
_W_BURST = 0.60
_W_TTR = 0.25
_W_PUNCT = 0.15


def _clamp01(value):
    """Keep a number inside [0, 1]."""
    return max(0.0, min(1.0, value))


def _linear_map(value, low, high):
    """Map `value` to 0-1 where `low` -> 1.0 and `high` -> 0.0 (and clamp).

    Used when a LOW raw metric means "more AI" (e.g. low burstiness).
    """
    if high == low:
        return 0.5
    return _clamp01((high - value) / (high - low))


def stylometric_signal(text):
    """Signal 2: measure structural text statistics in pure Python.

    Returns a dict:
        {
            "score": float,        # 0.0 - 1.0, higher = more likely AI
            "metrics": {...},      # the raw numbers, for transparency/audit
            "ok": bool,
        }

    The three metrics (sentence-length burstiness, type-token ratio, and
    punctuation density) are each turned into a 0-1 AI-likeness, then combined
    with a weighted average.
    """
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    sent_word_counts = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
    words = re.findall(r"\b\w+\b", text.lower())
    total_words = len(words)

    if total_words == 0:
        return {"score": 0.5, "metrics": {}, "ok": False}

    # Metric 1: sentence-length burstiness (coefficient of variation).
    mean_len = statistics.mean(sent_word_counts) if sent_word_counts else 0
    std_len = statistics.pstdev(sent_word_counts) if len(sent_word_counts) > 1 else 0
    cv_len = (std_len / mean_len) if mean_len else 0.0
    ai_burst = _linear_map(cv_len, _CV_LOW, _CV_HIGH)  # low CV -> more AI

    # Metric 2: type-token ratio (vocabulary diversity).
    ttr = len(set(words)) / total_words
    ai_ttr = _linear_map(ttr, _TTR_LOW, _TTR_HIGH)  # low diversity -> more AI

    # Metric 3: punctuation density.
    punct = len(re.findall(r"[,.;:!?\"'()\-]", text))
    punct_density = punct / total_words
    ai_punct = _clamp01(punct_density / _PUNCT_MAX)  # heavier punctuation -> more AI

    score = (_W_BURST * ai_burst) + (_W_TTR * ai_ttr) + (_W_PUNCT * ai_punct)
    score = _clamp01(score)

    return {
        "score": score,
        "metrics": {
            "n_words": total_words,
            "n_sentences": len(sentences),
            "mean_sentence_len": round(mean_len, 2),
            "cv_sentence_len": round(cv_len, 3),
            "type_token_ratio": round(ttr, 3),
            "punctuation_density": round(punct_density, 3),
            "ai_burst": round(ai_burst, 3),
            "ai_ttr": round(ai_ttr, 3),
            "ai_punct": round(ai_punct, 3),
        },
        "ok": True,
    }


if __name__ == "__main__":
    # Quick manual test: run `python signals.py` to try a few inputs.
    samples = {
        "human-casual": (
            "Ugh, Monday again. Spilled coffee on my one clean shirt, missed "
            "the bus by like ten seconds, and now my laptop won't even turn on. "
            "Some days you just gotta laugh, you know?"
        ),
        "ai-ish": (
            "In today's fast-paced world, effective time management is essential "
            "for achieving success. By prioritizing tasks and setting clear "
            "goals, individuals can maximize productivity and maintain a healthy "
            "work-life balance."
        ),
    }
    for name, sample in samples.items():
        result = llm_signal(sample)
        print(f"[{name}] score={result['score']:.2f} ok={result['ok']}")
        print(f"    reasoning: {result['reasoning']}")
